o = []
a = input('Введите возраст пользователя')
b = input('Введите пол пользователя')
c = input('Введите имя пользователя')
d = input('Введите город пользователя')
e = input('Класс пользователя')
o.append(a)
o.append(b)
o.append(c)
o.append(d)
o.append(e)
print(o)